# format = """
# [î‚¶](color_orange)\
# [î‚°](bg:color_yellow fg:color_orange)\
# $directory\
# [î‚°](fg:color_yellow bg:color_aqua)\
# $git_branch\
# $git_status\
# [î‚°](fg:color_aqua bg:color_blue)\
# $c\
# $rust\
# $nodejs\
# $python\
# [î‚°](fg:color_blue bg:color_bg3)\
# $docker_context\
# $conda\
# [î‚°](fg:color_bg3 bg:color_bg1)\
# $time\
# [î‚° ](fg:color_bg1)\
# $line_break$character"""
#
# palette = 'gruvbox_dark'
#
# [palettes.gruvbox_dark]
# color_fg0 = '#fbf1c7'
# color_bg1 = '#3c3836'
# color_bg3 = '#665c54'
# color_blue = '#458588'
# color_aqua = '#689d6a'
# color_green = '#98971a'
# color_orange = '#d65d0e'
# color_purple = '#b16286'
# color_red = '#cc241d'
# color_yellow = '#d79921'
#
# [username]
# show_always = true
# style_user = "bg:color_orange fg:color_fg0"
# style_root = "bg:color_orange fg:color_fg0"
# format = '[ $user ]($style)'
#
# [directory]
# style = "fg:color_fg0 bg:color_yellow"
# format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "â€¦/"
#
# [directory.substitutions]
# "Documents" = "ó°ˆ™ "
# "Downloads" = "ï€™ "
# "Music" = "ó°š "
# "Pictures" = "ï€¾ "
# "Developer" = "ó°²‹ "
#
# [git_branch]
# symbol = "ï˜"
# style = "bg:color_aqua"
# format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'
#
# [git_status]
# style = "bg:color_aqua"
# format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'
#
# [nodejs]
# symbol = "îœ˜"
# style = "bg:color_blue"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
#
# [c]
# symbol = "î˜ "
# style = "bg:color_blue"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
#
# [rust]
# symbol = "î¨"
# style = "bg:color_blue"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
#
# [python]
# symbol = "î˜†"
# style = "bg:color_blue"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
#
# [docker_context]
# symbol = "ïŒˆ"
# style = "bg:color_bg3"
# format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'
#
# [conda]
# style = "bg:color_bg3"
# format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'
#
# [time]
# disabled = false
# time_format = "%R"
# style = "bg:color_bg1"
# format = '[[ ïº $time ](fg:color_fg0 bg:color_bg1)]($style)'
#
# [line_break]
# disabled = false

##############

# # Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


add_newline = true

# $localip\
# $shlvl\
# $typst\
# $opa\
# $kubernetes\
# $terraform\
# $vagrant\
# $helm\
# $openstack\

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$dart\
$deno\
$gradle\
$lua\
$nodejs\
$python\
$rust\
$nix_shell\
$memory_usage\
$direnv\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$status\
$container\
$shell\
$character"""

palette = 'my_palette'

[palettes.my_palette]
_white   = "#ffffff"
_magenta = "#ff3366"
_light_gray = "#cccccc"
_dark_gray = "#333333"
_orange = "#ff6600"
_red = "#cc3300"
_yellow = "#ffcc00"
_green = "#33cc00"
_aqua = "#669966"

# XXX
color_blue = '#458588'
color_green = '#98971a'
color_purple = '#b16286'
color_yellow = '#d79921'

#[env_var.USER]
#default = 'unknown user'

# TODO use only emoji or not ?

[character]
success_symbol = " ğŸŸ¢"
error_symbol = " ğŸ”´"

[directory]
format = "[ ](bg:_white)[ğŸ“‚](fg:_dark_gray bg:_white)[ ](bg:_white)[ $path]($style)[ $read_only](bold fg:_magenta bg:_yellow)[ ](bg:_yellow)"
style = "bold fg:_white bg:_yellow"
truncation_length = 3
truncate_to_repo = true
home_symbol = "ğŸ "
read_only = "!!"
truncation_symbol = 'â€¦/'

[git_branch]
symbol = "ğŸŒ¿"
truncation_length = 10
truncation_symbol = "â€¦"
only_attached = false
always_show_remote = false
format = "[ ](bg:_white)[$symbol](fg:_dark_gray bg:_white)[ ](bg:_white)[ $branch(:$remote_name/$remote_branch)]($style)[ ](bg:_green)"
style = "fg:_white bg:_green"

[cmd_duration]
min_time = 2_000
show_milliseconds = false
format = "[ ](bg:_white)[ğŸ•‘](bg:_dark_gray bg:_white)[ ](bg:_white)[ $duration]($style)[ ](bg:_magenta)"
style="fg:_white bg:_magenta"

[direnv]
format = "[ ](bg:_white)[$symbol](bold fg:_dark_gray bg:_white)[ ](bg:_white)[ $allowed]($style)[ ](bg:_aqua)"
disabled = false
symbol = "env"
style = "fg:_white bg:_aqua"

[git_commit]
commit_hash_length = 5
tag_symbol = "ó°“¹ "
format = "[â–ˆ](fg:#ffffff bg:none)[îœ©](fg:_dark_gray bg:#ffffff)[â–ˆ](fg:#ffffff bg:#24c90a)[ $hash $tag]($style)[â–ˆ](fg:#24c90a bg:none) "
style = "fg:#ffffff bg:#24c90a"
only_detached = true
tag_disabled = false

[git_state]
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style =	"bold red"
format = "[$state( $progress_current/$progress_total)]($style) "
disabled = false


[git_metrics]
disabled = false
added_style = 'bold green'
deleted_style = 'bold red'
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'

[git_status]
format="[â–ˆ](fg:#ffffff bg:none)[ó±–« ](fg:_dark_gray bg:#ffffff)[â–ˆ ](fg:#ffffff bg:#4da0ff)[$modified](fg:_dark_gray bg:#4da0ff)[$untracked](fg:_dark_gray bg:#4da0ff)[$staged](fg:_dark_gray bg:#4da0ff)[$renamed](fg:_dark_gray bg:#4da0ff)[â–ˆ](fg:#4da0ff bg:none) "
#conflicted = ""
#ahead = "ğŸğŸ’¨"
#behind = "ğŸ˜°"
#diverged = "ğŸ˜µ"
#up_to_date = "ğŸ¥°"
#untracked = "ğŸ¤·"
#stashed = "ğŸ“¦"
#modified = "ğŸ“"
#renamed = "ğŸ‘…"
#deleted = "ğŸ—‘ï¸"
#style = "red"
disabled = false


[nodejs]
symbol = "ğŸ¤– "
disabled = true

[package]
symbol = "ğŸ“¦ "
disabled = true

[python]
# symbol = "î˜†ó±” "
symbol = "î˜† "

[rust]
symbol = "î¨ "

# [time]
# disabled = false
# format="[â–ˆ](fg:#ffffff bg:none)[ğŸ’–](fg:_dark_gray bg:#ffffff)[â–ˆ](fg:#ffffff bg:#f72851)[ $time]($style)[â–ˆ](fg:#f72851 bg:none)"
# time_format = "%T" #change to %R to only have HH:MM
# style="fg:#ffffff bg:#f72851"

# [custom.emoji]
# description = "Displays a (pseudo) random emoji for each prompt"
# command = "EMOJIS=(â›µï¸ ğŸ›° ğŸª ğŸš€ ğŸ§¡ ğŸ”­ ğŸŒ ğŸ’« â˜„ï¸ âœ¨ ğŸŒ  ğŸŒŒ â­ï¸); EMOJI_INDEX=$(( $RANDOM % 12 + 0 )); echo ${EMOJIS[$EMOJI_INDEX]}"
# when = "1"
# shell = ["cmd /C"]
# format = "$output"
